base_route: '/home/rauljcuesta/master/proyecto_master'
config_rouse: '/config'
data_route: '/data'
data_ganvam_route: '/ganvam'
data_dgt_route: '/dgt'
files_ganvam:
  - car_list_reverse_2015.csv.tar.gz
  - car_list_reverse_2016.csv.tar.gz
  - car_list_reverse_2017.csv.tar.gz
  - car_list_reverse_2018.csv.tar.gz
  - car_list_reverse_2019.csv.tar.gz
  - car_list_reverse_2020.csv.tar.gz
  - car_list_reverse_2021.csv.tar.gz
files_dgt:
  - export_anual_trf_2015.csv.tar.gz
  - export_anual_trf_2016.csv.tar.gz
  - export_anual_trf_2017.csv.tar.gz
  - export_anual_trf_2018.csv.tar.gz
  - export_anual_trf_2019.csv.tar.gz
  - export_anual_trf_2020.csv.tar.gz
  - export_anual_trf_2021.csv.tar.gz
csv_ganvam_separator : '^'
csv_dgt_separator : '^'
url_web_storage: 'https://storage.cloud.google.com/rauljcuesta_kschool_proyecto_master'
fields_dgt_originals:
  - FEC_MATRICULA
  - COD_CLASE_MAT
  - FEC_TRAMITACION
  - MARCA_ITV
  - MODELO_ITV
  - COD_PROCEDENCIA_ITV
  - BASTIDOR_ITV
  - COD_TIPO
  - COD_PROPULSION_ITV
  - CILINDRADA_ITV
  - POTENCIA_ITV
  - TARA
  - PESO_MAX
  - NUM_PLAZAS
  - IND_PRECINTO
  - IND_EMBARGO
  - NUM_TRANSMISIONES
  - NUM_TITULARES
  - LOCALIDAD_VEHICULO
  - COD_PROVINCIA_VEH
  - COD_PROVINCIA_MAT
  - CLAVE_TRAMITE
  - FEC_TRAMITE
  - CODIGO_POSTAL
  - FEC_PRIM_MATRICULACION
  - IND_NUEVO_USADO
  - PERSONA_FISICA_JURIDICA
  - CODIGO_ITV
  - SERVICIO
  - COD_MUNICIPIO_INE_VEH
  - MUNICIPIO
  - KW_ITV
  - NUM_PLAZAS_MAX
  - CO2_ITV
  - RENTING
  - COD_TUTELA
  - COD_POSESION
  - IND_BAJA_DEF
  - IND_BAJA_TEMP
  - IND_SUSTRACCION
  - BAJA_TELEMATICA
  - TIPO_ITV
  - VARIANTE_ITV
  - VERSION_ITV
  - FABRICANTE_ITV
  - MASA_ORDEN_MARCHA_ITV
  - MASA_MÁXIMA_TECNICA_ADMISIBLE_ITV
  - CATEGORÍA_HOMOLOGACIÓN_EUROPEA_ITV
  - CARROCERIA
  - PLAZAS_PIE
  - NIVEL_EMISIONES_EURO_ITV
  - CONSUMO_WH/KM_ITV
  - CLASIFICACIÓN_REGLAMENTO_VEHICULOS_ITV
  - CATEGORÍA_VEHÍCULO_ELÉCTRICO
  - AUTONOMÍA_VEHÍCULO_ELÉCTRICO
  - MARCA_VEHÍCULO_BASE
  - FABRICANTE_VEHÍCULO_BASE
  - TIPO_VEHÍCULO_BASE
  - VARIANTE_VEHÍCULO_BASE
  - VERSIÓN_VEHÍCULO_BASE
  - DISTANCIA_EJES_12
  - VIA_ANTERIOR_ITV
  - VIA_POSTERIOR_ITV
  - TIPO_ALIMENTACION_ITV
  - CONTRASEÑA_HOMOLOGACION_ITV
  - ECO_INNOVACION_ITV
  - REDUCCION_ECO_ITV
  - CODIGO_ECO_ITV
  - FEC_PROCESO
fields_dgt_process:
  - FEC_MATRICULA
  - COD_CLASE_MAT
  - FEC_TRAMITACION
  - MARCA_ITV
  - MODELO_ITV
  - COD_PROCEDENCIA_ITV
  - COD_PROPULSION_ITV
  - CILINDRADA_ITV
  - POTENCIA_ITV
  - NUM_PLAZAS
  - NUM_TRANSMISIONES
  - NUM_TITULARES
  - LOCALIDAD_VEHICULO
  - COD_PROVINCIA_VEH
  - COD_PROVINCIA_MAT
  - CLAVE_TRAMITE
  - FEC_TRAMITE
  - CODIGO_POSTAL
  - FEC_PRIM_MATRICULACION
  - IND_NUEVO_USADO
  - PERSONA_FISICA_JURIDICA
  - COD_MUNICIPIO_INE_VEH
  - MUNICIPIO
  - KW_ITV
  - NUM_PLAZAS_MAX
  - CO2_ITV
  - RENTING
  - CATEGORÍA_HOMOLOGACIÓN_EUROPEA_ITV
  - NIVEL_EMISIONES_EURO_ITV
  - CONSUMO_WH/KM_ITV
  - CATEGORÍA_VEHÍCULO_ELÉCTRICO
  - AUTONOMÍA_VEHÍCULO_ELÉCTRICO
  - year_Q
  - Q_query
fields_ganvam_process:
  - Q_query
  - year_Q
  - make
  - model
  - fuel
  - year_query
  - modelo
  - valor
  - cilindrada
  - puertas
  - potencia
  - startyear
  - endyear